/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareas;

import java.text.Normalizer;
import javax.swing.JOptionPane;

/**
 *
 * @author carlo
 */
public class Ejercicio4 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio4
     */
    
    public Ejercicio4() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();
        btnCambiar = new javax.swing.JButton();
        btnVoltear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtcadena = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Frank Ruehl CLM", 1, 20)); // NOI18N
        jLabel1.setText("Cadenas");

        jLabel2.setFont(new java.awt.Font("DejaVu Serif", 0, 15)); // NOI18N
        jLabel2.setText("Ingresa la cadena:");

        btnContar.setBackground(new java.awt.Color(51, 255, 102));
        btnContar.setText("Contar vocales");
        btnContar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarActionPerformed(evt);
            }
        });

        btnCambiar.setBackground(new java.awt.Color(51, 255, 102));
        btnCambiar.setText("Cambiar letras");
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });

        btnVoltear.setBackground(new java.awt.Color(51, 255, 102));
        btnVoltear.setText("Dar la vuelta");
        btnVoltear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltearActionPerformed(evt);
            }
        });

        txtcadena.setColumns(20);
        txtcadena.setRows(5);
        jScrollPane1.setViewportView(txtcadena);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoltear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(btnContar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCambiar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnVoltear)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarActionPerformed
        String cadena = txtcadena.getText();
        cadena = Normalizer.normalize(cadena, Normalizer.Form.NFD)
                .replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
        String[] arregloC = contarVocales(cadena);
        contarPalabras(cadena);
    }//GEN-LAST:event_btnContarActionPerformed

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed
        String cadena = txtcadena.getText();
        cadena = Normalizer.normalize(cadena, Normalizer.Form.NFD)
                .replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
        reemplazarLetras(cadena);
    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnVoltearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltearActionPerformed
        String cadena = txtcadena.getText();
        cadena = Normalizer.normalize(cadena, Normalizer.Form.NFD)
                .replaceAll("\\p{InCombiningDiacriticalMarks}+", "");
        String[] arregloC = contarVocales(cadena);
        mostrarCadenaAlReves(arregloC);
    }//GEN-LAST:event_btnVoltearActionPerformed
    public static void contarPalabras(String cadena) {
        String[] palabras = cadena.split("\\s+");
        int cantidadPalabras = palabras.length;
        JOptionPane.showMessageDialog(null, "Cantidad de palabras: " + cantidadPalabras);
    }

    public static void reemplazarLetras(String cadena) {
        String cadenaReemplazada = cadena.replace('o', '$').replace('a', '@');
        JOptionPane.showMessageDialog(null, "Cadena con letras reemplazadas: " + cadenaReemplazada);
    }

    public static String[] contarVocales(String cadenaT) {
        int a = 0, e = 0, i = 0, o = 0, u = 0, total = 0;
        String[] arregloCadena = cadenaT.split("");
        for (String s : arregloCadena) {
            if (s.equalsIgnoreCase("a")) {
                a++;
            } else if (s.equalsIgnoreCase("e")) {
                e++;
            } else if (s.equalsIgnoreCase("i")) {
                i++;
            } else if (s.equalsIgnoreCase("o")) {
                o++;
            } else if (s.equalsIgnoreCase("u")) {
                u++;
            }
        }

        total = a + e + i + o + u;

        JOptionPane.showMessageDialog(null,
                "El número de 'a' es igual a: " + a +
                        "\nEl número de 'e' es igual a: " + e +
                        "\nEl número de 'i' es igual a: " + i +
                        "\nEl número de 'o' es igual a: " + o +
                        "\nEl número de 'u' es igual a: " + u +
                        "\nEl total de vocales es igual a: " + total);
        return arregloCadena;
    }

    public static void mostrarCadenaAlReves(String[] arregloC) {
        StringBuilder cadenaAlReves = new StringBuilder();
        for (int i = arregloC.length - 1; i >= 0; i--) {
            cadenaAlReves.append(arregloC[i]);
        }
        JOptionPane.showMessageDialog(null, "Cadena al revés: " + cadenaAlReves.toString());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnContar;
    private javax.swing.JButton btnVoltear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtcadena;
    // End of variables declaration//GEN-END:variables
}
